# Generated by Django 3.2.16 on 2023-02-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='endurance',
            field=models.IntegerField(choices=[(1, 'Extremely Low'), (2, 'Very Low'), (3, 'Low'), (4, 'Moderately Low'), (5, 'Moderate'), (6, 'Moderately High'), (7, 'High'), (8, 'Very High'), (9, 'Extremely High'), (10, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='length',
            field=models.IntegerField(choices=[(1, 'Extremely Low'), (2, 'Very Low'), (3, 'Low'), (4, 'Moderately Low'), (5, 'Moderate'), (6, 'Moderately High'), (7, 'High'), (8, 'Very High'), (9, 'Extremely High'), (10, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='thickness',
            field=models.IntegerField(choices=[(1, 'Extremely Low'), (2, 'Very Low'), (3, 'Low'), (4, 'Moderately Low'), (5, 'Moderate'), (6, 'Moderately High'), (7, 'High'), (8, 'Very High'), (9, 'Extremely High'), (10, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='timeframe',
            field=models.IntegerField(choices=[(1, 'Extremely Low'), (2, 'Very Low'), (3, 'Low'), (4, 'Moderately Low'), (5, 'Moderate'), (6, 'Moderately High'), (7, 'High'), (8, 'Very High'), (9, 'Extremely High'), (10, 'Excellent')]),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Extremely Low'), (2, 'Very Low'), (3, 'Low'), (4, 'Moderately Low'), (5, 'Moderate'), (6, 'Moderately High'), (7, 'High'), (8, 'Very High'), (9, 'Extremely High'), (10, 'Excellent')]),
        ),
    ]
