# Generated by Django 3.2.16 on 2023-03-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_auto_20230213_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('0900', '09:00'), ('1030', '10:30'), ('1200', '12:00'), ('1530', '15:30'), ('1700', '17:00')], max_length=4)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
