# Generated by Django 3.2.16 on 2023-03-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_appointmenttimes_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentTimes',
            new_name='AppointmentTime',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
