# Generated by Django 3.2.16 on 2023-03-03 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_auto_20230301_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avatar',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
