# Generated by Django 3.2.16 on 2023-03-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0017_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
