# Generated by Django 3.2.16 on 2023-03-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0018_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='alt_text',
            field=models.CharField(default='package_image', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.FloatField(),
        ),
    ]
