# Generated by Django 3.2.16 on 2023-03-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0022_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='alt_text',
        ),
    ]
