# Generated by Django 3.2.16 on 2023-03-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0023_remove_package_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
