# Generated by Django 3.2.16 on 2023-03-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0024_package_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
    ]
