# Generated by Django 3.2.16 on 2023-03-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0025_remove_package_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
    ]
