# Generated by Django 3.2.16 on 2023-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0027_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('09:00', '0900'), ('10:30', '1030'), ('12:00', '1200'), ('15:30', '1530'), ('17:00', '1700')], max_length=5),
        ),
    ]
