# Generated by Django 3.2.16 on 2023-03-16 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0028_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
