# Generated by Django 3.2.16 on 2023-03-03 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20230303_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentTime',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('0900', '09:00'), ('1030', '10:30'), ('1200', '12:00'), ('1530', '15:30'), ('1700', '17:00')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
