# Generated by Django 3.2.16 on 2023-03-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_booking_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
