# Generated by Django 3.2.16 on 2023-03-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='body',
        ),
    ]
