# Generated by Django 3.2.16 on 2023-03-05 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_remove_review_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('time', models.CharField(choices=[('0900', '09:00'), ('1030', '10:30'), ('1200', '12:00'), ('1530', '15:30'), ('1700', '17:00')], max_length=4)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
