# Generated by Django 3.2.16 on 2023-03-11 17:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_remove_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
